// ========== 邮箱：保留旧收件能力，并扩展写信、线程、陌生人与笔友 ==========
(() => {
  const SETTINGS = { id:'main', backgroundEnabled:true, penpalEnabled:true, friendEnabled:true, mysteryEnabled:true, absurdEnabled:true, flirtEnabled:false, replyMode:'random', replyFixedDelay:10, replyDelayMin:2, replyDelayMax:30 };
  const BOXES = [
    ['treehole','深夜树洞','treehole@public.test','倾诉','匿名写下难以对熟人说出口的话。'],
    ['lost','城市失物招领','lost@public.test','生活','寻找失物、认领旧照片或帮助陌生人。'],
    ['penpal','笔友匹配中心','penpal@public.test','笔友','根据来信匹配愿意长期通信的人。'],
    ['mystery','都市传说调查局','cases@public.test','悬疑','投稿异常事件，也可能收到调查委托。'],
    ['future','未来邮局','future@public.test','时间','把信寄给未来，等待不合时宜的回信。'],
    ['exchange','旧物交换站','exchange@public.test','交换','描述想交换的旧物，等待陌生人回应。']
  ].map(x=>({id:'public_'+x[0],name:x[1],email:x[2],category:x[3],description:x[4]}));
  const FOLDERS={inbox:'收件箱',starred:'星标',sent:'已发送',drafts:'草稿',scheduled:'定时发送',spam:'垃圾邮件',trash:'已删除'};
  const REL={unknown:'未知发件人',correspondent:'有过通信',familiar:'熟悉的陌生人',penpal:'笔友',trusted_penpal:'可信赖笔友',contact_exchange_pending:'邀请交换联系方式',chat_friend:'聊天好友',mail_only:'仅接受邮件',suspicious:'身份存疑',blocked:'已拉黑',lost_contact:'已失联',institution:'公共机构'};
  const mailState={currentEmailId:null,currentThreadId:null,currentFolder:'inbox',currentContactId:null,contactFilter:'all',isEditMode:false,selectedEmails:new Set(),composeAttachments:[],composeDraftId:null,composeReplyToId:null,composeThreadId:null,contactReturnScreen:'email-screen',initialized:false,processingEvents:false,activeEventIds:new Set(),progressTimer:null,settingsCache:null};
  const txt=v=>String(v??'').trim(), id=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`, clamp=(v,a,b)=>{const n=Number(v);return Math.min(b,Math.max(a,Number.isFinite(n)?n:a))};
  const userName=()=>state?.globalSettings?.userNickname||state?.qzoneSettings?.nickname||'我';
  function hash(s){let h=2166136261;for(const c of String(s||'unknown')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
  function fakeEmail(v,fallback){v=txt(v).toLowerCase();return /^[^\s@]+@[^\s@]+\.(test|local|invalid)$/.test(v)?v:(fallback||`${hash(v)}@unknown.test`)}
  const time=t=>{const d=new Date(+t||Date.now());return d.toLocaleDateString()===new Date().toLocaleDateString()?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString()};

  async function mailSettings(){return {...SETTINGS,...(await db.mailSettings.get('main')||{}),...(mailState.settingsCache||{})}}
  async function ensureMailData(){
    if(mailState.initialized)return;
    await db.transaction('rw',db.mailAccounts,db.mailPublicBoxes,db.mailSettings,db.emails,db.mailContacts,db.mailThreads,async()=>{
      await db.mailAccounts.put({id:'main',email:'me@ephone.local',displayName:userName(),signature:'',isDefault:true,isAnonymous:false});
      if(!await db.mailAccounts.get('anonymous'))await db.mailAccounts.add({id:'anonymous',email:'anonymous@relay.test',displayName:'匿名用户',signature:'',isDefault:false,isAnonymous:true});
      for(const b of BOXES)await db.mailPublicBoxes.put(b);if(!await db.mailSettings.get('main'))await db.mailSettings.put({...SETTINGS});
      for(const old of await db.emails.toArray()){
        const direction=old.direction||'incoming', who=direction==='outgoing'?old.recipient:old.sender, key=(old.senderEmail||old.recipientEmail||who||old.id), contactId=old.contactId||`mail_contact_${hash(key)}`;
        if(!await db.mailContacts.get(contactId))await db.mailContacts.add({id:contactId,name:txt(who)||'未知发件人',email:fakeEmail(old.senderEmail||old.recipientEmail,`${hash(key)}@unknown.test`),relationshipStatus:'unknown',profileSummary:'',writingStyle:'',notes:'',trust:0,interactionCount:1,incomingCount:direction==='incoming'?1:0,outgoingCount:direction==='outgoing'?1:0,createdAt:old.timestamp||Date.now(),lastContactAt:old.timestamp||Date.now(),blocked:false,chatId:null});
        const uid=old.uid||id('mail'),threadId=old.threadId||`thread_${uid}`;
        await db.emails.put({...old,uid,threadId,contactId,direction,folder:old.folder||(direction==='outgoing'?'sent':'inbox'),status:old.status||(direction==='outgoing'?'sent':'delivered'),isRead:!!old.isRead,isStarred:!!old.isStarred,attachments:Array.isArray(old.attachments)?old.attachments:[],cc:old.cc||[],bcc:old.bcc||[]});
        if(!await db.mailThreads.get(threadId))await db.mailThreads.add({id:threadId,contactId,subject:old.subject||'无主题',status:'active',lastTimestamp:old.timestamp||Date.now(),createdAt:old.timestamp||Date.now()});
      }
    });for(const e of await db.mailEvents.where('status').equals('processing').toArray())if((e.startedAt||e.createdAt||0)<Date.now()-600000)await db.mailEvents.update(e.id,{status:'failed',failedAt:Date.now(),nextActionAt:e.replyMode==='manual'?null:Date.now(),error:'上次调用意外中断，可重新尝试'});mailState.initialized=true;
  }
  async function openEmailApp(){await ensureMailData();await processDueMailEvents(true,false);showScreen('email-screen');await setMailFolder(mailState.currentFolder)}
  async function setMailFolder(folder){mailState.currentFolder=FOLDERS[folder]?folder:'inbox';mailState.isEditMode=false;mailState.selectedEmails.clear();document.getElementById('mail-folder-title').textContent=FOLDERS[mailState.currentFolder];document.querySelectorAll('#mail-folder-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.folder===mailState.currentFolder));document.getElementById('mail-action-bar').style.display='none';document.getElementById('mail-edit-btn').textContent='编辑';await renderEmailList()}
  function durationText(ms){const total=Math.max(0,Math.ceil(ms/1000)),h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;if(h)return `${h}小时${m?m+'分钟':''}`;if(m)return `${m}分钟${s?s+'秒':''}`;return `${s}秒`}
  function isGeneratedReply(x){return !!(x&&x.direction==='incoming'&&(x.generatedBy==='mail_reply'||(x.replyToId&&x.senderType==='contact')))}
  function replyModeLabel(e){return {instant:'立即回复',fixed:'指定等待',random:'随机等待',manual:'仅手动'}[e?.replyMode]||'等待回复'}
  function eventSummary(e,now=Date.now()){
    if(!e)return null;
    if(e.status==='processing')return{title:'正在生成回信',detail:'AI 正在组织邮件内容，请稍候',percent:38,cls:'is-processing'};
    if(e.status==='completed')return{title:'已经收到回信',detail:e.completedAt?`实际用时 ${durationText(e.completedAt-e.createdAt)}`:'生成完成',percent:100,cls:'is-completed'};
    if(e.status==='cancelled')return{title:'已取消自动回信',detail:'可以随时手动生成',percent:0,cls:'is-cancelled'};
    if(e.status==='failed'){const retry=e.nextActionAt>now?`${durationText(e.nextActionAt-now)}后自动重试`:'可以立即重试';return{title:'回信生成失败',detail:`${txt(e.error)||'调用未完成'} · ${retry}`,percent:0,cls:'is-failed'}}
    if(e.replyMode==='manual'||!e.nextActionAt)return{title:'等待手动生成回信',detail:'不会自动调用 AI',percent:0,cls:'is-manual'};
    const total=Math.max(1,e.nextActionAt-e.createdAt),left=e.nextActionAt-now,percent=Math.max(0,Math.min(100,(now-e.createdAt)/total*100));
    return{title:left>0?`${replyModeLabel(e)}中`:'已到预计时间',detail:left>0?`本次 ${durationText(total)} · 还剩 ${durationText(left)} · 预计 ${new Date(e.nextActionAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'等待应用处理到期任务',percent,cls:'is-pending'}
  }
  function progressMarkup(e,compact=false){const s=eventSummary(e);if(!s)return'';return `<span class="${compact?'mail-inline-reply':'mail-reply-progress-inner'} ${s.cls}" data-mail-event-id="${escapeHTML(e.id)}" data-status="${escapeHTML(e.status)}" data-mode="${escapeHTML(e.replyMode||'')}" data-created="${Number(e.createdAt)||0}" data-next="${Number(e.nextActionAt)||0}" data-completed="${Number(e.completedAt)||0}" data-error="${escapeHTML(e.error||'')}">${compact?`<span class="mail-inline-reply-copy"><span class="mail-reply-title">${escapeHTML(s.title)}</span><span class="mail-reply-detail">${escapeHTML(s.detail)}</span></span>`:`<div class="mail-reply-progress-copy"><strong class="mail-reply-title">${escapeHTML(s.title)}</strong><small class="mail-reply-detail">${escapeHTML(s.detail)}</small></div>`}<span class="mail-reply-progress-track"><span class="mail-reply-progress-fill" style="width:${s.percent.toFixed(1)}%"></span></span></span>`}
  function refreshProgressClocks(){document.querySelectorAll('[data-mail-event-id]').forEach(el=>{const e={id:el.dataset.mailEventId,status:el.dataset.status,replyMode:el.dataset.mode,createdAt:+el.dataset.created,nextActionAt:+el.dataset.next,completedAt:+el.dataset.completed,error:el.dataset.error},s=eventSummary(e);if(!s)return;el.querySelector('.mail-reply-title').textContent=s.title;el.querySelector('.mail-reply-detail').textContent=s.detail;el.querySelector('.mail-reply-progress-fill').style.width=`${s.percent}%`})}
  async function renderEmailList(){
    await ensureMailData();const el=document.getElementById('email-list');if(!el)return;el.replaceChildren();let rows=await db.emails.orderBy('timestamp').reverse().toArray();rows=mailState.currentFolder==='starred'?rows.filter(x=>x.isStarred&&x.folder!=='trash'):rows.filter(x=>(x.folder||'inbox')===mailState.currentFolder);const eventBySource=new Map();for(const e of (await db.mailEvents.toArray()).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)))eventBySource.set(+e.sourceEmailId,e);
    const q=txt(document.getElementById('mail-search-input')?.value).toLowerCase(),contacts=new Map((await db.mailContacts.toArray()).map(x=>[x.id,x]));rows=rows.filter(x=>!q||[x.sender,x.recipient,x.subject,x.content,contacts.get(x.contactId)?.notes].some(v=>String(v||'').toLowerCase().includes(q)));
    if(!rows.length){el.innerHTML=`<div class="mail-empty-state"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg><strong>${q?'没有匹配的邮件':'这里还没有邮件'}</strong><span>${mailState.currentFolder==='inbox'?'可以检查新邮件，或主动写信认识陌生人。':'邮件会在相应操作后出现在这里。'}</span></div>`;return updateCounts()}
    for(const x of rows){const c=contacts.get(x.contactId),b=document.createElement('button');b.type='button';b.className=`mail-item ${x.isRead||x.direction==='outgoing'?'':'unread'} ${mailState.isEditMode?'editing':''}`;b.dataset.id=x.id;if(mailState.selectedEmails.has(x.id))b.classList.add('selected');const who=x.direction==='outgoing'?`致 ${x.recipient||c?.name||'收件人'}`:(x.sender||c?.name||'未知发件人'),replyEvent=x.direction==='outgoing'?eventBySource.get(+x.id):null;b.innerHTML=`<span class="mail-select-checkbox"></span><span class="mail-item-header"><span class="mail-sender">${escapeHTML(who)}</span><span class="mail-date">${escapeHTML(time(x.timestamp))}</span></span><span class="mail-subject">${x.isStarred?'<span class="mail-inline-star">★</span>':''}${escapeHTML(x.subject||'无主题')}</span><span class="mail-preview">${escapeHTML(txt(x.content).replace(/\n/g,' ').slice(0,120))}</span>${replyEvent?`<span class="mail-inline-reply">${progressMarkup(replyEvent,true)}</span>`:''}<span class="mail-item-footer"><span>${escapeHTML(REL[c?.relationshipStatus]||'')}</span><span>${x.attachments?.length?'附件 '+x.attachments.length:''}</span><span>${escapeHTML({draft:'草稿',scheduled:'等待发送',sent:'已发送',delivered:'已送达',read:'已打开',replied:'已回复'}[x.status]||'')}</span></span>`;b.onclick=()=>mailState.isEditMode?handleEmailSelection(b,x.id):openEmailDetail(x.id);el.appendChild(b)}refreshProgressClocks();await updateCounts()
  }
  async function updateCounts(){const n=(await db.emails.toArray()).filter(x=>(x.folder||'inbox')==='inbox'&&!x.isRead).length,el=document.getElementById('mail-count-inbox');if(el)el.textContent=n?String(n):''}
  function handleEmailSelection(el,i){mailState.selectedEmails.has(i)?mailState.selectedEmails.delete(i):mailState.selectedEmails.add(i);el.classList.toggle('selected',mailState.selectedEmails.has(i));updateMailDeleteButton()}
  function updateMailDeleteButton(){const b=document.getElementById('mail-delete-selected-btn'),n=mailState.selectedEmails.size;b.textContent=n?`删除 (${n})`:'删除';b.disabled=!n}
  async function executeBatchDeleteEmails(){const n=mailState.selectedEmails.size;if(!n)return;if(!await showCustomConfirm('删除邮件',`确定要删除这 ${n} 封邮件吗？此操作无法撤销。`,{confirmButtonClass:'btn-danger',confirmText:'删除'}))return;const ids=[...mailState.selectedEmails];for(const e of await db.mailEvents.toArray())if(ids.includes(+e.sourceEmailId)&&['pending','failed'].includes(e.status))await db.mailEvents.update(e.id,{status:'cancelled',cancelledAt:Date.now(),error:'关联邮件已删除'});await db.emails.bulkDelete(ids);mailState.selectedEmails.clear();await renderEmailList()}
  function handleSelectAllEmails(){const a=[...document.querySelectorAll('#email-list .mail-item')],on=mailState.selectedEmails.size<a.length;a.forEach(e=>{const i=+e.dataset.id;on?mailState.selectedEmails.add(i):mailState.selectedEmails.delete(i);e.classList.toggle('selected',on)});updateMailDeleteButton()}
  function toggleEmailEditMode(){mailState.isEditMode=!mailState.isEditMode;document.getElementById('mail-edit-btn').textContent=mailState.isEditMode?'完成':'编辑';document.getElementById('mail-action-bar').style.display=mailState.isEditMode?'flex':'none';mailState.selectedEmails.clear();renderEmailList()}
  async function openEmailDetail(i){
    const possibleDraft=await db.emails.get(+i);if(['drafts','scheduled'].includes(possibleDraft?.folder))return openMailCompose({draftId:possibleDraft.id});
    const x=await db.emails.get(+i);if(!x)return;mailState.currentEmailId=x.id;mailState.currentThreadId=x.threadId;mailState.currentContactId=x.contactId;if(!x.isRead)await db.emails.update(x.id,{isRead:true,readAt:Date.now(),status:x.direction==='outgoing'?x.status:'read'});
    const thread=x.threadId?await db.emails.where('threadId').equals(x.threadId).sortBy('timestamp'):[x],c=await db.mailContacts.get(x.contactId);document.getElementById('mail-detail-subject').textContent=x.subject||'无主题';document.getElementById('mail-detail-from').textContent=x.sender||c?.name||'未知发件人';document.getElementById('mail-detail-to').textContent=x.recipient||userName();document.getElementById('mail-detail-time').textContent=new Date(x.timestamp||Date.now()).toLocaleString();document.getElementById('mail-detail-avatar').textContent=txt(x.sender||c?.name||'?')[0];
    const body=document.getElementById('mail-detail-body'),list=document.getElementById('mail-thread-list');body.textContent='';list.replaceChildren();if(thread.length===1)body.textContent=x.content||'';else thread.forEach(m=>{const a=document.createElement('article');a.className='mail-thread-message '+m.direction;a.innerHTML=`<div class="mail-thread-message-header"><strong>${escapeHTML(m.direction==='outgoing'?userName():m.sender)}</strong><span>${escapeHTML(new Date(m.timestamp).toLocaleString())}</span></div>`;const p=document.createElement('div');p.className='mail-thread-message-content';p.textContent=m.content||'';a.appendChild(p);list.appendChild(a)});renderAttachments(document.getElementById('mail-detail-attachments'),x.attachments||[],false);document.getElementById('mail-detail-status').textContent=REL[c?.relationshipStatus]||'';document.getElementById('mail-detail-star-btn').classList.toggle('active',!!x.isStarred);document.getElementById('mail-move-spam-btn').textContent=x.folder==='spam'?'移回收件箱':'垃圾邮件';await renderReplyControls(x);showScreen('email-detail-screen')
  }
  async function latestReplyEvent(sourceEmailId){return (await db.mailEvents.toArray()).filter(e=>+e.sourceEmailId===+sourceEmailId&&e.type==='generate_reply').sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))[0]||null}
  async function renderReplyControls(x){
    const box=document.getElementById('mail-reply-progress'),tools=document.getElementById('mail-generated-reply-tools'),editor=document.getElementById('mail-generated-editor');if(!box||!tools)return;
    box.hidden=true;box.replaceChildren();tools.hidden=true;if(editor)editor.hidden=true;
    if(x.direction==='outgoing'&&x.folder!=='drafts'&&x.folder!=='scheduled'){
      const e=await latestReplyEvent(x.id);if(e){const summary=eventSummary(e),head=document.createElement('div');box.hidden=false;box.className=`mail-reply-progress ${summary.cls}`;head.className='mail-reply-progress-head';head.innerHTML=progressMarkup(e,false);box.appendChild(head);const actions=document.createElement('div');actions.className='mail-reply-progress-actions';const add=(label,fn,cls='')=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cls;b.disabled=e.status==='processing';b.onclick=fn;actions.appendChild(b)};if(e.status!=='completed')add(e.status==='failed'?'立即重试':'立即生成回信',()=>immediateReplyForEmail(x.id));if(['pending','failed'].includes(e.status)&&e.replyMode!=='manual')add('调整时间',()=>adjustReplyTime(e.id));if(['pending','failed'].includes(e.status))add('取消等待',()=>cancelReplyEvent(e.id),'mail-reply-cancel');if(e.status==='cancelled')add('重新启用',()=>adjustReplyTime(e.id));if(actions.childElementCount)box.appendChild(actions);refreshProgressClocks()}
    }
    if(isGeneratedReply(x)){tools.hidden=false}
  }
  async function immediateReplyForEmail(emailId){let e=await latestReplyEvent(emailId),x=await db.emails.get(+emailId);if(!x)return;if(!e){const c=await db.mailContacts.get(x.contactId);e=await event('generate_reply',c?.id,x.threadId,x.id,Date.now(),{replyMode:'instant',totalDelayMinutes:0})}else if(e.status==='completed'||e.status==='processing')return;else{await db.mailEvents.update(e.id,{status:'pending',nextActionAt:Date.now(),error:null});e=await db.mailEvents.get(e.id)}await renderReplyControls(x);await processMailEvent(e,false,true);if(mailState.currentEmailId===x.id)await openEmailDetail(x.id);else await renderEmailList()}
  async function adjustReplyTime(eventId){const e=await db.mailEvents.get(eventId);if(!e)return;const choice=await showChoiceModal('调整回信时间',[{text:'5 分钟后',value:'5'},{text:'15 分钟后',value:'15'},{text:'30 分钟后',value:'30'},{text:'1 小时后',value:'60'},{text:'仅手动调用',value:'manual'},{text:'自定义分钟',value:'custom'}]);if(!choice)return;let minutes=choice==='manual'?null:Number(choice);if(choice==='custom'){const v=await showCustomPrompt('自定义等待时间','请输入等待分钟数（0～10080）：','10');if(v===null)return;minutes=clamp(v,0,10080)}const now=Date.now();await db.mailEvents.update(eventId,{status:'pending',replyMode:minutes===null?'manual':'fixed',createdAt:now,nextActionAt:minutes===null?null:now+minutes*60000,totalDelayMinutes:minutes,error:null});const x=await db.emails.get(e.sourceEmailId);if(x)await renderReplyControls(x)}
  async function cancelReplyEvent(eventId){const e=await db.mailEvents.get(eventId);if(!e||e.status==='processing')return;await db.mailEvents.update(eventId,{status:'cancelled',cancelledAt:Date.now()});const x=await db.emails.get(e.sourceEmailId);if(x)await renderReplyControls(x)}
  function beginGeneratedEdit(){const x=db.emails.get(mailState.currentEmailId);x.then(m=>{if(!m)return;document.getElementById('mail-edit-generated-subject').value=m.subject||'';document.getElementById('mail-edit-generated-content').value=m.content||'';document.getElementById('mail-generated-editor').hidden=false})}
  async function saveGeneratedEdit(){const x=await db.emails.get(mailState.currentEmailId);if(!isGeneratedReply(x))return;const subject=txt(document.getElementById('mail-edit-generated-subject').value)||'无主题',content=txt(document.getElementById('mail-edit-generated-content').value);if(!content)return showCustomAlert('无法保存','回信正文不能为空。');const history=[...(x.revisionHistory||[]),{subject:x.subject,content:x.content,savedAt:Date.now(),source:'manual'}].slice(-20);await db.emails.update(x.id,{subject,content,revisionHistory:history,originalSubject:x.originalSubject||x.subject,originalContent:x.originalContent||x.content,generatedBy:'mail_reply',manuallyEdited:true});await openEmailDetail(x.id);showCustomAlert('已保存','回信内容已更新，可从“历史”恢复。')}
  async function regenerateCurrentReply(){
    const x=await db.emails.get(mailState.currentEmailId);if(!isGeneratedReply(x))return;let guidance=await showChoiceModal('让对方重说',[{text:'自然地换一种说法',value:'natural'},{text:'更简短',value:'short'},{text:'更详细',value:'detailed'},{text:'更冷淡',value:'cool'},{text:'更热情',value:'warm'},{text:'自定义要求',value:'custom'}]);if(!guidance)return;if(guidance==='custom'){guidance=await showCustomPrompt('自定义重说要求','描述希望对方怎样重新回复：','换一种自然、不重复的表达');if(!txt(guidance))return}const thread=await db.emails.where('threadId').equals(x.threadId).sortBy('timestamp'),hasLater=thread.some(m=>(m.timestamp||0)>(x.timestamp||0));if(hasLater&&!await showCustomConfirm('保留通信顺序','这封回信之后已经有新的通信。重说结果将作为一封新的补充回信，不会覆盖旧记录。',{confirmText:'继续生成'}))return;const b=document.getElementById('mail-regenerate-btn'),old=b.textContent;b.disabled=true;b.textContent='生成中…';try{const e=await db.mailEvents.get(x.sourceEventId)||{id:x.sourceEventId||id('mail_event'),type:'generate_reply',contactId:x.contactId,threadId:x.threadId,sourceEmailId:x.replyToId},r=await requestReplyData(e,guidance,x.id),subject=txt(r.subject)||x.subject,content=txt(r.content)||x.content;if(hasLater){const latestOutgoing=thread.filter(m=>m.direction==='outgoing').at(-1),newId=await db.emails.add({uid:id('mail'),threadId:x.threadId,contactId:x.contactId,direction:'incoming',folder:'inbox',status:'delivered',sender:txt(r.senderName)||x.sender,senderEmail:fakeEmail(r.senderEmail,x.senderEmail),senderType:'contact',recipient:userName(),recipientEmail:'me@ephone.local',subject,content,originalSubject:subject,originalContent:content,revisionHistory:[],generatedBy:'mail_reply',sourceEventId:e.id,attachments:[],timestamp:Date.now(),isRead:false,isStarred:false,replyToId:latestOutgoing?.id||x.replyToId});const c=await db.mailContacts.get(x.contactId);if(c)await db.mailContacts.update(c.id,{incomingCount:(c.incomingCount||0)+1,interactionCount:(c.interactionCount||0)+1,lastContactAt:Date.now()});await openEmailDetail(newId);showCustomAlert('已生成补充回信','旧通信记录保持不变。')}else{const history=[...(x.revisionHistory||[]),{subject:x.subject,content:x.content,savedAt:Date.now(),source:'regenerate'}].slice(-20);await db.emails.update(x.id,{subject,content,revisionHistory:history,originalSubject:x.originalSubject||x.subject,originalContent:x.originalContent||x.content,generatedBy:'mail_reply',manuallyEdited:false});await openEmailDetail(x.id)}}catch(err){showCustomAlert('重说失败',err.message)}finally{b.disabled=false;b.textContent=old}}
  async function showReplyHistory(){const x=await db.emails.get(mailState.currentEmailId);if(!x)return;const revisions=x.revisionHistory||[],choices=[];if(x.originalContent)choices.push({text:'恢复最初生成内容',value:'original'});revisions.slice().reverse().forEach((r,i)=>choices.push({text:`恢复 ${new Date(r.savedAt).toLocaleString()} 的内容`,value:`revision:${revisions.length-1-i}`}));if(!choices.length)return showCustomAlert('暂无历史','这封回信还没有可恢复的旧内容。');const choice=await showChoiceModal('回信历史',choices);if(!choice)return;const old={subject:x.subject,content:x.content,savedAt:Date.now(),source:'restore'},target=choice==='original'?{subject:x.originalSubject,content:x.originalContent}:revisions[+choice.split(':')[1]];if(!target)return;await db.emails.update(x.id,{subject:target.subject,content:target.content,revisionHistory:[...revisions,old].slice(-20),manuallyEdited:true});await openEmailDetail(x.id)}
  function closeEmailDetail(){showScreen('email-screen');renderEmailList()}
  async function deleteEmail(i){if(!await showCustomConfirm('删除邮件','确定要删除这封邮件吗？此操作无法撤销。',{confirmButtonClass:'btn-danger',confirmText:'删除'}))return false;for(const e of await db.mailEvents.toArray())if(+e.sourceEmailId===+i&&['pending','failed'].includes(e.status))await db.mailEvents.update(e.id,{status:'cancelled',cancelledAt:Date.now(),error:'关联邮件已删除'});await db.emails.delete(+i);return true}
  async function deleteCurrentEmail(){if(mailState.currentEmailId&&await deleteEmail(mailState.currentEmailId))closeEmailDetail()}
  async function star(){const x=await db.emails.get(mailState.currentEmailId);await db.emails.update(x.id,{isStarred:!x.isStarred});openEmailDetail(x.id)}
  async function spam(){const x=await db.emails.get(mailState.currentEmailId),folder=x.folder==='spam'?'inbox':'spam';await db.emails.update(x.id,{folder});closeEmailDetail();showCustomAlert(folder==='spam'?'已移入垃圾邮件':'已恢复','邮件仍可从对应文件夹查看。')}

  async function openMailCompose(o={}){
    await ensureMailData();mailState.composeAttachments=[];mailState.composeDraftId=o.draftId||null;mailState.composeReplyToId=o.replyToId||null;mailState.composeThreadId=o.threadId||null;const a=document.getElementById('mail-compose-account'),r=document.getElementById('mail-compose-recipient');a.replaceChildren();r.replaceChildren(new Option('手动输入地址','manual'),new Option('随机漂流信','random'));(await db.mailAccounts.toArray()).forEach(x=>a.add(new Option(`${x.displayName} <${x.email}>`,x.id)));const g=document.createElement('optgroup');g.label='联系人与笔友';(await db.mailContacts.orderBy('lastContactAt').reverse().toArray()).filter(x=>!x.blocked).forEach(x=>g.appendChild(new Option(`${x.name} <${x.email}>`,`contact:${x.id}`)));r.appendChild(g);const pg=document.createElement('optgroup');pg.label='公共邮箱';(await db.mailPublicBoxes.toArray()).forEach(x=>pg.appendChild(new Option(`${x.name} <${x.email}>`,`public:${x.id}`)));r.appendChild(pg);
    ['mail-compose-recipient-address','mail-compose-cc','mail-compose-bcc','mail-compose-subject','mail-compose-body'].forEach(i=>document.getElementById(i).value='');document.getElementById('mail-compose-anonymous').checked=false;document.getElementById('mail-compose-receipt').checked=false;document.getElementById('mail-compose-schedule-toggle').checked=false;document.getElementById('mail-compose-scheduled-at').disabled=true;const settings=await mailSettings();document.getElementById('mail-compose-reply-mode').value='default';document.getElementById('mail-compose-fixed-delay').value=settings.replyFixedDelay;document.getElementById('mail-compose-random-min').value=settings.replyDelayMin;document.getElementById('mail-compose-random-max').value=settings.replyDelayMax;
    let x=o.draftId?await db.emails.get(+o.draftId):o.replyToId?await db.emails.get(+o.replyToId):null;if(x){const c=await db.mailContacts.get(x.contactId);if(c)r.value=`contact:${c.id}`;document.getElementById('mail-compose-subject').value=o.replyToId&&!/^re:/i.test(x.subject||'')?'Re: '+x.subject:x.subject||'';document.getElementById('mail-compose-body').value=o.draftId?x.content||'':'';mailState.composeAttachments=o.draftId?[...(x.attachments||[])]:[];mailState.composeThreadId=x.threadId;document.getElementById('mail-compose-title').textContent=o.draftId?'编辑草稿':'回复邮件';if(o.draftId){document.getElementById('mail-compose-reply-mode').value=x.replyModeChoice||'default';document.getElementById('mail-compose-fixed-delay').value=x.replyFixedDelay??settings.replyFixedDelay;document.getElementById('mail-compose-random-min').value=x.replyDelayMin??settings.replyDelayMin;document.getElementById('mail-compose-random-max').value=x.replyDelayMax??settings.replyDelayMax}}else{document.getElementById('mail-compose-title').textContent='新邮件';if(o.contactId)r.value=`contact:${o.contactId}`;if(o.publicBoxId)r.value=`public:${o.publicBoxId}`;if(o.recipientMode==='random')r.value='random';document.getElementById('mail-compose-subject').value=o.subject||'';document.getElementById('mail-compose-body').value=o.body||''}syncComposeReplyOptions();await syncRecipient();renderAttachments(document.getElementById('mail-compose-attachments'),mailState.composeAttachments,true);showScreen('email-compose-screen')
  }
  function syncComposeReplyOptions(){const mode=document.getElementById('mail-compose-reply-mode')?.value||'default',box=document.getElementById('mail-compose-reply-options'),fixed=document.getElementById('mail-compose-fixed-wrap'),random=document.getElementById('mail-compose-random-wrap');if(!box)return;box.hidden=!['fixed','random'].includes(mode);if(fixed)fixed.hidden=mode!=='fixed';if(random)random.hidden=mode!=='random';updateComposeReplyHint()}
  async function updateComposeReplyHint(){const hint=document.getElementById('mail-compose-hint'),mode=document.getElementById('mail-compose-reply-mode')?.value||'default';if(!hint)return;const s=await mailSettings(),resolved=mode==='default'?s.replyMode:mode;let text={instant:'发送后将立即生成回信。',manual:'发送后等待你手动调用回信。'}[resolved];if(resolved==='fixed')text=`发送后约 ${clamp(mode==='default'?s.replyFixedDelay:document.getElementById('mail-compose-fixed-delay').value,0,10080)} 分钟生成回信。`;if(resolved==='random'){const min=clamp(mode==='default'?s.replyDelayMin:document.getElementById('mail-compose-random-min').value,0,10080),max=Math.max(min,clamp(mode==='default'?s.replyDelayMax:document.getElementById('mail-compose-random-max').value,0,10080));text=`发送后将在 ${min}～${max} 分钟内随机生成回信。`}hint.textContent=`${text||''} 取消时可选择保存为草稿；AI 辅助不会自动发送。`}
  async function syncRecipient(){const r=document.getElementById('mail-compose-recipient'),v=r.value,i=document.getElementById('mail-compose-recipient-address');if(v.startsWith('contact:'))i.value=(await db.mailContacts.get(v.slice(8)))?.email||'';else if(v.startsWith('public:'))i.value=(await db.mailPublicBoxes.get(v.slice(7)))?.email||'';else if(v==='random')i.value='random@drift.test';i.disabled=v!=='manual'}
  async function recipient(){const v=document.getElementById('mail-compose-recipient').value,address=txt(document.getElementById('mail-compose-recipient-address').value).toLowerCase();if(v.startsWith('contact:'))return db.mailContacts.get(v.slice(8));if(v.startsWith('public:')){const b=await db.mailPublicBoxes.get(v.slice(7)),cid='mail_contact_'+b.id;let c=await db.mailContacts.get(cid);if(!c){c={id:cid,name:b.name,email:b.email,relationshipStatus:'institution',profileSummary:b.description,writingStyle:'机构邮件',notes:'',trust:20,interactionCount:0,incomingCount:0,outgoingCount:0,createdAt:Date.now(),lastContactAt:Date.now(),blocked:false,publicBoxId:b.id,chatId:null};await db.mailContacts.add(c)}return c}if(v==='random'){const cid=id('mail_contact'),c={id:cid,name:'等待陌生人收信',email:`${hash(cid)}@drift.test`,relationshipStatus:'unknown',profileSummary:'通过漂流邮件偶然相遇。',writingStyle:'',notes:'',trust:0,interactionCount:0,incomingCount:0,outgoingCount:0,createdAt:Date.now(),lastContactAt:Date.now(),blocked:false,isDrift:true,chatId:null};await db.mailContacts.add(c);return c}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address))return null;let c=await db.mailContacts.where('email').equals(address).first();if(!c){c={id:id('mail_contact'),name:address.split('@')[0],email:address,relationshipStatus:'unknown',profileSummary:'',writingStyle:'',notes:'',trust:0,interactionCount:0,incomingCount:0,outgoingCount:0,createdAt:Date.now(),lastContactAt:Date.now(),blocked:false,chatId:null};await db.mailContacts.add(c)}return c}
  function composeRecord(c,a,status,folder){const min=clamp(document.getElementById('mail-compose-random-min')?.value,0,10080),max=Math.max(min,clamp(document.getElementById('mail-compose-random-max')?.value,0,10080));return{uid:id('mail'),threadId:mailState.composeThreadId||id('thread'),contactId:c?.id||null,direction:'outgoing',folder,status,sender:a?.displayName||userName(),senderEmail:a?.email||'me@ephone.local',recipient:c?.name||'',recipientEmail:c?.email||'',cc:txt(document.getElementById('mail-compose-cc').value).split(/[,，;]/).filter(Boolean),bcc:txt(document.getElementById('mail-compose-bcc').value).split(/[,，;]/).filter(Boolean),subject:txt(document.getElementById('mail-compose-subject').value)||'无主题',content:txt(document.getElementById('mail-compose-body').value),attachments:[...mailState.composeAttachments],timestamp:Date.now(),isRead:true,isStarred:false,isAnonymous:document.getElementById('mail-compose-anonymous').checked,requestReceipt:document.getElementById('mail-compose-receipt').checked,replyToId:mailState.composeReplyToId,replyModeChoice:document.getElementById('mail-compose-reply-mode')?.value||'default',replyFixedDelay:clamp(document.getElementById('mail-compose-fixed-delay')?.value,0,10080),replyDelayMin:min,replyDelayMax:max}}
  async function saveDraft(){const c=await recipient(),a=await db.mailAccounts.get('main'),x=composeRecord(c,a,'draft','drafts');if(mailState.composeDraftId){x.id=+mailState.composeDraftId;await db.emails.put(x)}else mailState.composeDraftId=await db.emails.add(x);await showCustomAlert('草稿已保存','可以在“草稿”文件夹继续编辑。')}
  async function closeMailCompose(){const has=['mail-compose-recipient-address','mail-compose-subject','mail-compose-body'].some(i=>txt(document.getElementById(i).value))||mailState.composeAttachments.length;if(has){const c=await showChoiceModal('保留这封邮件？',[{text:'保存草稿',value:'save'},{text:'不保存',value:'discard'},{text:'继续编辑',value:'cancel'}]);if(c==='cancel'||c===null)return;if(c==='save')await saveDraft()}showScreen('email-screen');renderEmailList()}
  async function sendCompose(){
    const body=txt(document.getElementById('mail-compose-body').value);if(!body)return showCustomAlert('无法发送','请先填写邮件正文。');const c=await recipient();if(!c)return showCustomAlert('收件地址无效','请选择联系人，或输入有效邮箱地址。');if(c.blocked)return showCustomAlert('无法发送','该联系人已被拉黑。');const a=await db.mailAccounts.get(document.getElementById('mail-compose-anonymous').checked?'anonymous':document.getElementById('mail-compose-account').value),scheduled=document.getElementById('mail-compose-schedule-toggle').checked,at=scheduled?new Date(document.getElementById('mail-compose-scheduled-at').value).getTime():null;if(scheduled&&(!at||at<=Date.now()))return showCustomAlert('定时时间无效','请选择晚于当前时间的发送时间。');const x=composeRecord(c,a,scheduled?'scheduled':'sent',scheduled?'scheduled':'sent');x.scheduledAt=at;if(mailState.composeDraftId){x.id=+mailState.composeDraftId;await db.emails.put(x)}else x.id=await db.emails.add(x);await db.mailThreads.put({id:x.threadId,contactId:c.id,subject:x.subject,status:'active',lastTimestamp:x.timestamp,createdAt:x.timestamp});await db.mailContacts.update(c.id,{relationshipStatus:c.relationshipStatus==='unknown'?'correspondent':c.relationshipStatus,outgoingCount:(c.outgoingCount||0)+1,interactionCount:(c.interactionCount||0)+1,lastContactAt:x.timestamp});let replyEvent=null;if(scheduled)await event('send_scheduled',c.id,x.threadId,x.id,at);else replyEvent=await scheduleReply(x,c);mailState.currentFolder=scheduled?'scheduled':'sent';showScreen('email-screen');await setMailFolder(mailState.currentFolder);const summary=replyEvent?eventSummary(replyEvent):null,replyCopy=replyEvent?.replyMode==='instant'||replyEvent?.totalDelayMinutes===0?'正在立即生成回信。':replyEvent?.replyMode==='manual'?'已设为仅手动调用，可在邮件详情中点击“立即生成回信”。':summary?.detail||'已建立回信任务。';showCustomAlert(scheduled?'已安排发送':'邮件已发送',scheduled?'邮件会在指定时间寄出，寄出后按所选方式等待回信。':replyCopy);if(replyEvent&&(replyEvent.replyMode==='instant'||replyEvent.totalDelayMinutes===0))processMailEvent(replyEvent,true,true).then(()=>renderEmailList()).catch(console.error)
  }
  async function event(type,contactId,threadId,sourceEmailId,nextActionAt,extra={}){const row={id:id('mail_event'),type,status:'pending',contactId,threadId,sourceEmailId,nextActionAt,createdAt:Date.now(),attempts:0,...extra};await db.mailEvents.add(row);return row}
  async function scheduleReply(x,c){
    const s=await mailSettings(),choice=x.replyModeChoice&&x.replyModeChoice!=='default'?x.replyModeChoice:(x.replyMode||s.replyMode||'random');let delay=null;if(choice==='instant')delay=0;else if(choice==='fixed')delay=clamp(x.replyFixedDelay??s.replyFixedDelay,0,10080);else if(choice==='random'){const min=clamp(x.replyDelayMin??s.replyDelayMin,0,10080),max=Math.max(min,clamp(x.replyDelayMax??s.replyDelayMax,0,10080));delay=min+Math.random()*(max-min)}const now=Date.now();return event('generate_reply',c.id,x.threadId,x.id,delay===null?null:now+delay*60000,{replyMode:choice,totalDelayMinutes:delay,configuredDelayMin:choice==='random'?(x.replyDelayMin??s.replyDelayMin):undefined,configuredDelayMax:choice==='random'?(x.replyDelayMax??s.replyDelayMax):undefined})
  }
  async function callAI(system,user){const{proxyUrl,apiKey,model}=state.apiConfig||{};if(!proxyUrl||!model)throw Error('请先配置 API 和模型');const gemini=proxyUrl.includes('generativelanguage'),cfg=toGeminiRequestData(model,apiKey,system,[{role:'user',content:user}]),res=gemini?await fetch(cfg.url,cfg.data):await fetch(`${proxyUrl}/v1/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${apiKey}`},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:state.globalSettings?.apiTemperature??.9})});if(!res.ok)throw Error(`API 请求失败（${res.status}）`);const raw=getGeminiResponseText(await res.json()),m=String(raw).match(/```(?:json)?\s*([\s\S]*?)```/i),str=m?m[1]:String(raw).slice(String(raw).indexOf('{'),String(raw).lastIndexOf('}')+1);try{return JSON.parse(str)}catch{throw Error('AI 返回格式无法解析')}}
  async function processMailEvent(eventRow,silent=false,manual=false){
    if(!eventRow||mailState.activeEventIds.has(eventRow.id))return false;let claimed=false,current=null;await db.transaction('rw',db.mailEvents,async()=>{current=await db.mailEvents.get(eventRow.id);if(current&&['pending','failed'].includes(current.status)&&(manual||current.nextActionAt&&current.nextActionAt<=Date.now())){await db.mailEvents.update(current.id,{status:'processing',startedAt:Date.now(),attempts:(current.attempts||0)+1,error:null});claimed=true}});if(!claimed)return false;mailState.activeEventIds.add(current.id);const source=await db.emails.get(current.sourceEmailId);if(source&&mailState.currentEmailId===source.id)await renderReplyControls(source);if(document.getElementById('email-screen')?.classList.contains('active'))await renderEmailList();try{if(current.type==='send_scheduled'){const x=await db.emails.get(current.sourceEmailId),c=await db.mailContacts.get(current.contactId);if(x){await db.emails.update(x.id,{folder:'sent',status:'sent',timestamp:Date.now()});const replyEvent=await scheduleReply({...x,timestamp:Date.now()},c);if(replyEvent.replyMode==='instant'||replyEvent.totalDelayMinutes===0)setTimeout(()=>processMailEvent(replyEvent,true,true).then(()=>renderEmailList()).catch(console.error),0)}}else if(current.type==='generate_reply'){const replyId=await generateReply(current);await db.mailEvents.update(current.id,{resultEmailId:replyId})}await db.mailEvents.update(current.id,{status:'completed',completedAt:Date.now(),error:null});return true}catch(err){console.error(err);await db.mailEvents.update(current.id,{status:'failed',failedAt:Date.now(),nextActionAt:current.replyMode==='manual'?null:Date.now()+300000,error:err.message||String(err)});if(!silent)showCustomAlert('检查邮件失败',err.message||String(err));return false}finally{mailState.activeEventIds.delete(current.id);const refreshed=await db.emails.get(current.sourceEmailId);if(refreshed&&mailState.currentEmailId===refreshed.id)await renderReplyControls(refreshed);if(document.getElementById('email-screen')?.classList.contains('active'))await renderEmailList()}}
  async function processDueMailEvents(silent=false,force=false){if(mailState.processingEvents||!(await mailSettings()).backgroundEnabled)return 0;mailState.processingEvents=true;let n=0;try{const now=Date.now(),all=(await db.mailEvents.toArray()).filter(e=>['pending','failed'].includes(e.status)&&e.nextActionAt&&e.nextActionAt<=now).sort((a,b)=>a.nextActionAt-b.nextActionAt).slice(0,5);for(const e of all)if(await processMailEvent(e,silent,false))n++;if(n){await renderEmailList();const detail=document.getElementById('email-detail-screen');if(detail?.classList.contains('active')&&mailState.currentEmailId)await openEmailDetail(mailState.currentEmailId)}return n}finally{mailState.processingEvents=false}}
  async function requestReplyData(e,guidance='',excludeEmailId=null){const c=await db.mailContacts.get(e.contactId);if(!c||c.blocked)throw Error(c?.blocked?'该联系人已被拉黑':'联系人不存在');const thread=(await db.emails.where('threadId').equals(e.threadId).sortBy('timestamp')).filter(x=>+x.id!==+excludeEmailId),s=await mailSettings(),cfg=loadMailConfig()||{},history=thread.slice(-8).map(x=>`${x.direction==='outgoing'?userName():c.name}: ${x.content}`).join('\n\n'),guide={natural:'自然地换一种说法，不要复述原句。',short:'回复更简短，保留重点。',detailed:'回复更详细具体。',cool:'语气更克制冷淡，但仍符合人物。',warm:'语气更热情亲近，但不要脱离人物。'}[guidance]||guidance;const prompt=`你是通过邮件与用户通信的陌生人或机构。联系人：${c.name}；档案：${c.profileSummary||'未知'}；关系：${REL[c.relationshipStatus]||c.relationshipStatus}；用户身份：${cfg.userMask||'普通用户'}；世界：${cfg.worldContext||'现代生活'}。\n通信记录：\n${history}\n${c.isDrift?'请创建稳定具体的新笔友身份。':''}\n${s.penpalEnabled?'可自然发展为笔友。':'不要发展笔友。'}${s.friendEnabled?'关系成熟时可提出交换联系方式。':'不要交换联系方式。'}${s.mysteryEnabled?'可有合理悬疑。':''}${s.absurdEnabled?'可有符合世界观的荒诞元素。':''}${s.flirtEnabled?'允许克制暧昧。':'不要主动暧昧。'}${guide?`\n本次重写要求：${guide}`:''}不得索取现实敏感信息。可以拒绝或保持边界。只返回JSON：{"senderName":"稳定姓名","senderEmail":".test虚构邮箱","subject":"主题","content":"完整正文","profileSummary":"人物档案","writingStyle":"风格","relationshipStatus":"correspondent|familiar|penpal|trusted_penpal|contact_exchange_pending|mail_only|suspicious|lost_contact|institution","trustDelta":0}`;return callAI(prompt,guidance?'按要求重新回复用户邮件。':'回复用户邮件。')}
  async function generateReply(e){
    const c=await db.mailContacts.get(e.contactId),src=await db.emails.get(e.sourceEmailId);if(!src)throw Error('原始邮件不存在');const existing=(await db.emails.where('threadId').equals(e.threadId).toArray()).find(m=>m.sourceEventId===e.id);if(existing){await db.emails.update(src.id,{status:'replied'});return existing.id}const r=await requestReplyData(e),allowed=['correspondent','familiar','penpal','trusted_penpal','contact_exchange_pending','mail_only','suspicious','lost_contact','institution'],rel=allowed.includes(r.relationshipStatus)?r.relationshipStatus:(c.relationshipStatus==='unknown'?'correspondent':c.relationshipStatus),name=txt(r.senderName)||c.name,email=fakeEmail(r.senderEmail,c.email),subject=txt(r.subject)||(/^re:/i.test(src.subject)?src.subject:'Re: '+src.subject),content=txt(r.content)||'谢谢你的来信。';let replyId;await db.transaction('rw',db.mailContacts,db.emails,async()=>{await db.mailContacts.update(c.id,{name,email,profileSummary:txt(r.profileSummary)||c.profileSummary,writingStyle:txt(r.writingStyle)||c.writingStyle,relationshipStatus:rel,trust:clamp((c.trust||0)+clamp(r.trustDelta,-10,10),-100,100),incomingCount:(c.incomingCount||0)+1,interactionCount:(c.interactionCount||0)+1,lastContactAt:Date.now(),isDrift:false});replyId=await db.emails.add({uid:id('mail'),threadId:e.threadId,contactId:c.id,direction:'incoming',folder:'inbox',status:'delivered',sender:name,senderEmail:email,senderType:'contact',recipient:userName(),recipientEmail:'me@ephone.local',subject,content,originalSubject:subject,originalContent:content,revisionHistory:[],generatedBy:'mail_reply',sourceEventId:e.id,attachments:[],timestamp:Date.now(),isRead:false,isStarred:false,replyToId:src.id});await db.emails.update(src.id,{status:'replied'})});return replyId
  }
  async function attachments(ev){for(const f of [...ev.target.files].slice(0,5-mailState.composeAttachments.length)){if(f.size>5242880){await showCustomAlert('附件过大',`${f.name} 超过 5MB。`);continue}const dataUrl=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});mailState.composeAttachments.push({id:id('attachment'),name:f.name,type:f.type,size:f.size,dataUrl})}ev.target.value='';renderAttachments(document.getElementById('mail-compose-attachments'),mailState.composeAttachments,true)}
  function renderAttachments(el,arr,edit){if(!el)return;el.replaceChildren();arr.forEach(a=>{const x=document.createElement(edit?'div':'a');x.className='mail-attachment-chip';if(!edit){x.href=a.dataUrl||'#';x.download=a.name;x.target='_blank'}const s=document.createElement('span');s.textContent=`${a.name} · ${Math.ceil((a.size||0)/1024)}KB`;x.appendChild(s);if(edit){const b=document.createElement('button');b.type='button';b.textContent='×';b.onclick=()=>{mailState.composeAttachments=mailState.composeAttachments.filter(v=>v.id!==a.id);renderAttachments(el,mailState.composeAttachments,true)};x.appendChild(b)}el.appendChild(x)})}
  async function assist(){const body=document.getElementById('mail-compose-body'),sub=document.getElementById('mail-compose-subject'),op=await showChoiceModal('AI 写作辅助',[{text:body.value.trim()?'润色当前正文':'根据主题起草',value:'draft'},{text:'写得更正式',value:'formal'},{text:'写得更委婉',value:'gentle'},{text:'缩短并提取重点',value:'shorten'},{text:'检查隐私与表达',value:'check'}]);if(!op)return;try{const r=await callAI(`邮件写作助手。操作：${op}。主题：${sub.value}。正文：${body.value}。不得添加现实隐私。只返回JSON：{"subject":"主题","content":"正文","note":"提示"}`,'完善邮件。');if(op!=='check'){sub.value=txt(r.subject)||sub.value;body.value=txt(r.content)||body.value}document.getElementById('mail-compose-hint').textContent=txt(r.note)||'请确认内容后发送。'}catch(e){showCustomAlert('AI 辅助失败',e.message)}}

  async function openMailContacts(){await ensureMailData();mailState.contactReturnScreen='email-screen';showScreen('mail-contacts-screen');renderContacts()}
  function closeMailContacts(){showScreen('email-screen');renderEmailList()}
  async function renderContacts(){const el=document.getElementById('mail-contact-list');el.replaceChildren();let a=await db.mailContacts.orderBy('lastContactAt').reverse().toArray();a=a.filter(c=>!c.publicBoxId&&(mailState.contactFilter==='all'||(mailState.contactFilter==='penpal'?['penpal','trusted_penpal'].includes(c.relationshipStatus):c.relationshipStatus===mailState.contactFilter)));if(!a.length)el.innerHTML='<div class="mail-contact-empty">暂无符合条件的联系人。回复陌生邮件后会保留在这里。</div>';a.forEach(c=>{const b=document.createElement('button');b.className='mail-contact-item';b.innerHTML=`<span class="mail-contact-avatar">${escapeHTML(txt(c.name)[0]||'?')}</span><span class="mail-contact-main"><strong>${escapeHTML(c.name)}</strong><small>${escapeHTML(c.email)}</small></span><span class="mail-relation-badge">${escapeHTML(REL[c.relationshipStatus]||'联系人')}</span>`;b.onclick=()=>openMailContactDetail(c.id,'mail-contacts-screen');el.appendChild(b)});const p=document.getElementById('mail-public-box-list');p.replaceChildren();(await db.mailPublicBoxes.toArray()).forEach(b=>{const x=document.createElement('button');x.className='mail-public-box';x.innerHTML=`<span><strong>${escapeHTML(b.name)}</strong><small>${escapeHTML(b.description)}</small></span><em>${escapeHTML(b.category)}</em>`;x.onclick=()=>openMailCompose({publicBoxId:b.id});p.appendChild(x)})}
  async function openMailContactDetail(cid,back='email-detail-screen'){const c=await db.mailContacts.get(cid);if(!c)return;mailState.currentContactId=cid;mailState.contactReturnScreen=back;const mails=await db.emails.where('contactId').equals(cid).toArray(),el=document.getElementById('mail-contact-detail');el.innerHTML=`<div class="mail-contact-profile"><div class="mail-contact-profile-avatar">${escapeHTML(txt(c.name)[0]||'?')}</div><h2>${escapeHTML(c.name)}</h2><p>${escapeHTML(c.email)}</p><span class="mail-relation-badge">${escapeHTML(REL[c.relationshipStatus]||'联系人')}</span></div><div class="mail-contact-card"><label>人物档案</label><p>${escapeHTML(c.profileSummary||'通信仍然不多，身份尚不明确。')}</p><label>写信风格</label><p>${escapeHTML(c.writingStyle||'尚未形成稳定印象')}</p><label>私人备注</label><textarea id="mail-contact-notes" placeholder="只有你能看到">${escapeHTML(c.notes||'')}</textarea><button class="mail-secondary-btn" id="mail-save-contact-notes">保存备注</button></div><div class="mail-contact-stats"><span><strong>${c.incomingCount||0}</strong>来信</span><span><strong>${c.outgoingCount||0}</strong>寄出</span><span><strong>${mails.length}</strong>全部邮件</span></div><div class="mail-contact-actions" id="mail-contact-actions"></div>`;document.getElementById('mail-save-contact-notes').onclick=async()=>{await db.mailContacts.update(cid,{notes:document.getElementById('mail-contact-notes').value.trim()});showCustomAlert('已保存','联系人备注已更新。')};const ac=document.getElementById('mail-contact-actions'),add=(label,fn,cls='')=>{const b=document.createElement('button');b.className='mail-contact-action '+cls;b.textContent=label;b.onclick=fn;ac.appendChild(b)};add('写邮件',()=>openMailCompose({contactId:cid}));if(['unknown','correspondent','familiar'].includes(c.relationshipStatus))add('邀请成为笔友',()=>openMailCompose({contactId:cid,subject:'以后也继续写信吧',body:`你好，${c.name}：\n\n如果你愿意，我希望以后还能继续和你通信。\n\n${userName()}`}));if(c.relationshipStatus==='contact_exchange_pending')add('接受联系方式邀请',()=>makeFriend(cid,'谢谢你愿意交换联系方式，我们在聊天里见。'));if(!c.chatId&&!['blocked','lost_contact','institution'].includes(c.relationshipStatus))add('询问即时联系方式',()=>requestFriend(cid));if(c.chatId)add('进入聊天',()=>{showScreen('chat-screen');renderChatInterface(c.chatId)});add(c.relationshipStatus==='suspicious'?'取消可疑标记':'标记身份存疑',async()=>{await db.mailContacts.update(cid,{relationshipStatus:c.relationshipStatus==='suspicious'?'correspondent':'suspicious'});openMailContactDetail(cid,back)});add(c.blocked?'解除拉黑':'拉黑联系人',()=>block(cid),c.blocked?'':'danger');showScreen('mail-contact-detail-screen')}
  function closeMailContactDetail(){showScreen(mailState.contactReturnScreen);if(mailState.contactReturnScreen==='mail-contacts-screen')renderContacts()}
  async function block(cid){const c=await db.mailContacts.get(cid),on=!c.blocked;if(!await showCustomConfirm(on?'拉黑联系人':'解除拉黑',on?'拉黑后停止生成新回信，已有邮件保留。':'解除后可以继续通信。',{confirmText:on?'拉黑':'解除'}))return;await db.mailContacts.update(cid,{blocked:on,relationshipStatus:on?'blocked':'correspondent'});if(on)for(const e of await db.mailEvents.where('contactId').equals(cid).toArray())if(['pending','failed'].includes(e.status))await db.mailEvents.update(e.id,{status:'cancelled',cancelledAt:Date.now(),error:'联系人已拉黑'});openMailContactDetail(cid,mailState.contactReturnScreen)}
  async function requestFriend(cid){const c=await db.mailContacts.get(cid),reason=await showCustomPrompt('询问即时联系方式',`写下想对“${c.name}”说明的理由：`,'如果你愿意，我们可以交换即时联系方式。');if(!txt(reason))return;const mails=await db.emails.where('contactId').equals(cid).sortBy('timestamp'),ctx=mails.slice(-10).map(x=>`${x.direction==='outgoing'?userName():c.name}: ${x.content}`).join('\n');try{const r=await callAI(`你是${c.name}。档案：${c.profileSummary||'未知'}。通信：${ctx}。用户提出交换联系方式：“${reason}”。真实决定，不要无条件同意。只返回JSON：{"decision":"accept|reject|wait|mail_only","content":"完整邮件回应"}`,'决定是否交换联系方式。');await db.emails.add({uid:id('mail'),threadId:mails.at(-1)?.threadId||id('thread'),contactId:cid,direction:'incoming',folder:'inbox',status:'delivered',sender:c.name,senderEmail:c.email,recipient:userName(),subject:'Re: 关于联系方式',content:txt(r.content),attachments:[],timestamp:Date.now(),isRead:false,isStarred:false});if(r.decision==='accept')await makeFriend(cid,r.content);else if(r.decision==='mail_only')await db.mailContacts.update(cid,{relationshipStatus:'mail_only'});showCustomAlert(r.decision==='accept'?'已交换联系方式':'对方暂未同意',r.decision==='accept'?'已进入 AI 聊天列表，邮件仍会保留。':'你们仍可继续通过邮件联系。');openMailContactDetail(cid,'mail-contacts-screen')}catch(e){showCustomAlert('请求失败',e.message)}}
  async function makeFriend(cid,greeting){const c=await db.mailContacts.get(cid);if(c.chatId)return;const chatId=id('chat'),mails=await db.emails.where('contactId').equals(cid).sortBy('timestamp'),summary=mails.slice(-20).map(x=>`${x.direction==='outgoing'?userName():c.name}: ${x.content}`).join('\n\n').slice(0,6000),chat={id:chatId,name:c.name,originalName:c.name,isGroup:false,isPinned:false,unreadCount:0,relationship:{status:'friend',blockedTimestamp:null,applicationReason:'',source:'mail',mailContactId:cid},status:{text:'在线',lastUpdate:Date.now(),isBusy:false},settings:{aiPersona:`你是用户通过邮件认识的联系人。人物档案：${c.profileSummary||'部分未知'}。表达习惯：${c.writingStyle||'延续邮件风格'}。记得此前通信。`,myPersona:loadMailConfig()?.userMask||'我是谁呀。',myNickname:userName(),maxMemory:10,aiAvatar:defaultAvatar,myAvatar:defaultAvatar,background:'',theme:'default',fontSize:13,customCss:'',linkedWorldBookIds:[],aiAvatarLibrary:[],myAvatarLibrary:[],enableBackgroundActivity:true,actionCooldownMinutes:15,enableTimePerception:true,isOfflineMode:false,offlineMinLength:100,offlineMaxLength:300,offlinePresetId:null,offlineContinuousLayout:false,timeZone:'Asia/Shanghai',myPhoneLockScreenEnabled:false,myPhoneLockScreenPassword:'',userStatus:{text:'在线',lastUpdate:Date.now(),isBusy:false}},history:[{role:'system',content:`[邮件往来摘录]\n${summary}`,timestamp:Date.now()-1,isHidden:true},{role:'assistant',senderName:c.name,content:txt(greeting)||'终于可以在这里聊天了。',timestamp:Date.now()}],musicData:{totalTime:0},longTermMemory:[],thoughtsHistory:[],mailContactId:cid};state.chats[chatId]=chat;await db.chats.put(chat);await db.mailContacts.update(cid,{chatId,relationshipStatus:'chat_friend'});renderChatList()}

  function saveMailConfig(){const c={userMask:txt(document.getElementById('mail-user-mask').value),worldContext:txt(document.getElementById('mail-world-context').value),personaId:document.getElementById('mail-user-persona-select').value,allowRandom:document.getElementById('mail-allow-random-npc').checked,genCount:document.getElementById('mail-gen-count').value,selectedSenders:[...document.querySelectorAll('#mail-sender-list input:checked')].map(x=>x.value),selectedBookIds:[...document.querySelectorAll('#mail-context-list input:checked')].map(x=>x.value)};localStorage.setItem('ephone_mail_config',JSON.stringify(c));const mode=['instant','fixed','random','manual'].includes(document.getElementById('mail-reply-mode')?.value)?document.getElementById('mail-reply-mode').value:'random',s={...SETTINGS,backgroundEnabled:document.getElementById('mail-background-enabled')?.checked!==false,penpalEnabled:document.getElementById('mail-penpal-enabled')?.checked!==false,friendEnabled:document.getElementById('mail-friend-enabled')?.checked!==false,mysteryEnabled:document.getElementById('mail-mystery-enabled')?.checked!==false,absurdEnabled:document.getElementById('mail-absurd-enabled')?.checked!==false,flirtEnabled:!!document.getElementById('mail-flirt-enabled')?.checked,replyMode:mode,replyFixedDelay:clamp(document.getElementById('mail-reply-fixed-delay')?.value,0,10080),replyDelayMin:clamp(document.getElementById('mail-reply-delay-min')?.value,0,10080),replyDelayMax:clamp(document.getElementById('mail-reply-delay-max')?.value,0,10080)};s.replyDelayMax=Math.max(s.replyDelayMin,s.replyDelayMax);mailState.settingsCache=s;db.mailSettings.put(s);return c}
  function loadMailConfig(){try{return JSON.parse(localStorage.getItem('ephone_mail_config'))}catch{return null}}
  async function openEmailSettings(){await ensureMailData();const ps=document.getElementById('mail-user-persona-select');ps.innerHTML='<option value="">-- 仅使用下方关键词 (无详细人设) --</option>';if(state.activeChatId&&state.chats[state.activeChatId]?.settings?.myPersona)ps.add(new Option('当前聊天设定','current_chat'));(state.personaPresets||[]).forEach((p,i)=>ps.add(new Option(`人设库: ${(p.persona||`预设 ${i+1}`).slice(0,20)}...`,p.id)));const sl=document.getElementById('mail-sender-list');sl.replaceChildren();const people=[...Object.values(state.chats).filter(x=>!x.isGroup),...await db.npcs.toArray()];people.forEach(p=>{const l=document.createElement('label');l.className='gr-checkbox-item';const i=document.createElement('input');i.type='checkbox';i.value=p.name;const s=document.createElement('span');s.textContent=p.name;l.append(i,s);sl.appendChild(l)});const wl=document.getElementById('mail-context-list');wl.replaceChildren();(await db.worldBooks.toArray()).forEach(b=>{const l=document.createElement('label');l.className='gr-checkbox-item';const i=document.createElement('input');i.type='checkbox';i.value=b.id;const s=document.createElement('span');s.textContent=b.name;l.append(i,s);wl.appendChild(l)});const c=loadMailConfig();if(c){document.getElementById('mail-user-mask').value=c.userMask||'普通用户';document.getElementById('mail-world-context').value=c.worldContext||'';ps.value=c.personaId||'';document.getElementById('mail-gen-count').value=c.genCount||3;document.getElementById('mail-allow-random-npc').checked=c.allowRandom!==false;(c.selectedSenders||[]).forEach(v=>{const x=[...sl.querySelectorAll('input')].find(i=>i.value===v);if(x)x.checked=true});(c.selectedBookIds||[]).forEach(v=>{const x=[...wl.querySelectorAll('input')].find(i=>i.value===String(v));if(x)x.checked=true})}const s=await mailSettings();['background','penpal','friend','mystery','absurd','flirt'].forEach(k=>{const e=document.getElementById(`mail-${k}-enabled`);if(e)e.checked=!!s[k+'Enabled']});document.getElementById('mail-reply-mode').value=s.replyMode||'random';document.getElementById('mail-reply-fixed-delay').value=s.replyFixedDelay??10;document.getElementById('mail-reply-delay-min').value=s.replyDelayMin;document.getElementById('mail-reply-delay-max').value=s.replyDelayMax;syncSettingsReplyMode();document.getElementById('email-generator-modal').classList.add('visible')}
  function syncSettingsReplyMode(){const mode=document.getElementById('mail-reply-mode')?.value||'random',fixed=document.getElementById('mail-fixed-delay-wrap'),random=document.querySelector('#email-generator-modal .mail-delay-grid');if(fixed)fixed.hidden=mode!=='fixed';if(random)random.hidden=mode!=='random'}
  async function executeEmailGeneration(c){const n=clamp(c.genCount||3,1,10);let persona=c.personaId==='current_chat'?state.chats[state.activeChatId]?.settings?.myPersona||'':state.personaPresets?.find(p=>p.id===c.personaId)?.persona||'',books='';for(const bid of c.selectedBookIds||[]){const b=await db.worldBooks.get(bid);if(b)books+=`《${b.name}》:${(Array.isArray(b.content)?b.content:[]).filter(e=>e.enabled!==false).map(e=>e.content).join(';')}\n`}let chars='';Object.values(state.chats).filter(x=>!x.isGroup&&(c.selectedSenders||[]).includes(x.name)).forEach(x=>{chars+=`${x.name}人设:${String(x.settings.aiPersona||'').slice(0,500)}\n记忆:${getMemoryContextForPrompt(x)||'暂无'}\n`});try{const r=await callAI(`为用户生成${n}封多样自然邮件。身份:${c.userMask}；详细:${persona}；世界:${c.worldContext||'现代生活'}；世界书:${books}；指定人物:${chars}；${c.allowRandom?'允许陌生人、通知和垃圾邮件。':'只用指定人物。'}只返回JSON：{"emails":[{"sender":"姓名","senderEmail":".test虚构邮箱","subject":"主题","content":"正文","timestampOffset":0,"kind":"daily|stranger|institution|mystery|spam","profileSummary":"档案","writingStyle":"风格"}]}`,'生成邮件。'),arr=r.emails||[];for(const m of arr.slice(0,n)){const em=fakeEmail(m.senderEmail,`${hash(m.sender)}@unknown.test`);let ct=await db.mailContacts.where('email').equals(em).first();if(!ct){ct={id:id('mail_contact'),name:txt(m.sender)||'未知发件人',email:em,relationshipStatus:m.kind==='institution'?'institution':m.kind==='mystery'?'suspicious':'unknown',profileSummary:txt(m.profileSummary),writingStyle:txt(m.writingStyle),notes:'',trust:0,interactionCount:1,incomingCount:1,outgoingCount:0,createdAt:Date.now(),lastContactAt:Date.now(),blocked:false,chatId:null};await db.mailContacts.add(ct)}const uid=id('mail'),threadId='thread_'+uid,t=Date.now()-Math.max(0,+m.timestampOffset||0)*60000;await db.emails.add({uid,threadId,contactId:ct.id,direction:'incoming',folder:m.kind==='spam'?'spam':'inbox',status:'delivered',sender:ct.name,senderEmail:em,senderType:m.kind||'gen',recipient:c.userMask,recipientEmail:'me@ephone.local',subject:txt(m.subject)||'无主题',content:txt(m.content),attachments:[],timestamp:t,isRead:false,isStarred:false});await db.mailThreads.add({id:threadId,contactId:ct.id,subject:m.subject||'无主题',status:'active',lastTimestamp:t,createdAt:t})}await renderEmailList();await showCustomAlert('接收成功',`收到 ${Math.min(arr.length,n)} 封新邮件。`)}catch(e){showCustomAlert('接收失败',e.message)}}
  async function handleQuickReceiveMail(){const done=await processDueMailEvents(false),c=loadMailConfig();if(!c?.userMask){if(done)return showCustomAlert('检查完成',`收到 ${done} 封到期邮件。`);await showCustomAlert('提示','请先点击齿轮配置收件人身份和背景。');return openEmailSettings()}await showCustomAlert('正在接收...',`正在根据保存的配置 (${c.userMask}) 生成邮件...`);await executeEmailGeneration(c)}
  async function forwardEmailToChat(x){await openShareTargetPicker();const old=document.getElementById('confirm-share-target-btn'),b=old.cloneNode(true);old.parentNode.replaceChild(b,old);b.onclick=async()=>{const ids=[...document.querySelectorAll('.share-target-checkbox:checked')].map(c=>c.dataset.chatId);if(!ids.length)return showCustomAlert('请选择聊天','至少选择一个聊天。');for(const cid of ids){const t=state.chats[cid];if(!t)continue;t.history.push({role:'user',type:'forwarded_email',timestamp:Date.now(),content:`[邮件] ${x.subject}`,emailData:{subject:x.subject,sender:x.sender,date:new Date(x.timestamp).toLocaleString(),preview:txt(x.content).replace(/\n/g,' ').slice(0,100),fullContent:x.content}});t.history.push({role:'system',content:`[系统提示：用户转发了“${x.sender}”的邮件。]\n主题:${x.subject}\n${x.content}`,timestamp:Date.now()+1,isHidden:true});await db.chats.put(t)}document.getElementById('share-target-modal').classList.remove('visible');showCustomAlert('转发成功','邮件已以卡片形式发送。')}}
  async function generateFromSettings(){const c=saveMailConfig();if(!c.userMask)return showCustomAlert('缺少身份','请设置收件人身份。');const b=document.getElementById('start-generate-email-btn'),s=b.textContent;b.disabled=true;b.textContent='生成中...';try{await executeEmailGeneration(c);document.getElementById('email-generator-modal').classList.remove('visible')}finally{b.disabled=false;b.textContent=s}}
  function saveMailSettingsOnly(){saveMailConfig();document.getElementById('email-generator-modal').classList.remove('visible');showCustomAlert('设置已保存','新的回信方式会用于之后发送的邮件。')}
  function initMailAppBindings(){if(document.body.dataset.mailBindingsReady)return;document.body.dataset.mailBindingsReady='1';const on=(i,e,f)=>document.getElementById(i)?.addEventListener(e,f);on('mail-delete-selected-btn','click',executeBatchDeleteEmails);on('mail-select-all-btn','click',handleSelectAllEmails);on('start-generate-email-btn','click',generateFromSettings);on('save-mail-settings-btn','click',saveMailSettingsOnly);on('mail-search-input','input',renderEmailList);on('mail-folder-tabs','click',e=>{const b=e.target.closest('button[data-folder]');if(b)setMailFolder(b.dataset.folder)});on('mail-detail-star-btn','click',star);on('forward-email-btn','click',async()=>{const x=await db.emails.get(mailState.currentEmailId);if(x)forwardEmailToChat(x)});on('delete-email-btn','click',deleteCurrentEmail);on('mail-reply-btn','click',()=>openMailCompose({replyToId:mailState.currentEmailId}));on('mail-contact-btn','click',()=>openMailContactDetail(mailState.currentContactId,'email-detail-screen'));on('mail-move-spam-btn','click',spam);on('mail-compose-cancel-btn','click',closeMailCompose);on('mail-compose-send-btn','click',sendCompose);on('mail-compose-recipient','change',syncRecipient);on('mail-compose-attachment-input','change',attachments);on('mail-ai-assist-btn','click',assist);on('mail-compose-schedule-toggle','change',e=>document.getElementById('mail-compose-scheduled-at').disabled=!e.target.checked);on('mail-compose-reply-mode','change',syncComposeReplyOptions);['mail-compose-fixed-delay','mail-compose-random-min','mail-compose-random-max'].forEach(i=>on(i,'input',updateComposeReplyHint));on('mail-reply-mode','change',syncSettingsReplyMode);on('mail-edit-generated-btn','click',beginGeneratedEdit);on('mail-regenerate-btn','click',regenerateCurrentReply);on('mail-reply-history-btn','click',showReplyHistory);on('mail-cancel-generated-edit','click',()=>document.getElementById('mail-generated-editor').hidden=true);on('mail-save-generated-edit','click',saveGeneratedEdit);on('mail-contact-filter','click',e=>{const b=e.target.closest('button[data-filter]');if(b){mailState.contactFilter=b.dataset.filter;document.querySelectorAll('#mail-contact-filter button').forEach(x=>x.classList.toggle('active',x===b));renderContacts()}});setInterval(()=>processDueMailEvents(true,false),60000);mailState.progressTimer=setInterval(refreshProgressClocks,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshProgressClocks();processDueMailEvents(true,false)}})}
  Object.assign(window,{mailState,openEmailApp,renderEmailList,setMailFolder,handleEmailSelection,updateMailDeleteButton,executeBatchDeleteEmails,handleSelectAllEmails,openEmailDetail,closeEmailDetail,toggleEmailEditMode,deleteEmail,deleteCurrentEmail,saveMailConfig,loadMailConfig,openEmailSettings,handleQuickReceiveMail,executeEmailGeneration,forwardEmailToChat,openMailCompose,closeMailCompose,openMailContacts,closeMailContacts,openMailContactDetail,closeMailContactDetail,initMailAppBindings,processDueMailEvents,immediateReplyForEmail});
})();
